[project]
name = "chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-cli>=0.0.8",
    "fastapi[standart]>=0.116.0",
    "ipython>=9.4.0",
    "pre-commit>=4.2.0",
    "uvicorn>=0.35.0",
]
